
‚
v++_compile_a$825735a5-d81f-477e-b1bb-09f9a7d60aa82tl/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4/.tlog/v++_compile_a.xtl 2..compile_summary 2..compile_summary.pb d/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/..compile_summary.pb"Thu Jun  4 05:13:46 2020(˚µÓÙß.bÌ
$ae9c64b3-b2e0-4bbd-9fd5-9606235aab46v++b/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4/a/a.steps.log"Ö
/curr/software/Vitis/Vitis/2019.2/bin/unwrapped/lnx64.o/v++  --xp "vivado_prop:run.__KERNEL__.{STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS}={-directive sdx_optimization_effort_high}" --xp param:compiler.forceHlsDesignXmlGeneration=1 -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L1/include/hw -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/ -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/include/ -g -t sw_emu --platform /curr/software/Vitis/Vitis/2019.2/platforms/xilinx_u250_xdma_201830_2/xilinx_u250_xdma_201830_2.xpfm --save-temps --config /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/advanced.ini -DPARALLEL_BLOCK=12 --temp_dir hls4 --report_dir hls4_report -c -k zlib_top --report_level estimate -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/ /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_lz77_compress_mm.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_huffman_enc_mm.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_treegen_mm.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_s2_pingpong_buffer.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_top_loop.cpp *H-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L1/include/hw*B-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/*F-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/include/*-g*-t*sw_emu*
--platform*d/curr/software/Vitis/Vitis/2019.2/platforms/xilinx_u250_xdma_201830_2/xilinx_u250_xdma_201830_2.xpfm*--save-temps*--config*\/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/advanced.ini*-DPARALLEL_BLOCK=12*
--temp_dir*hls4*--report_dir*hls4_report*-c*-k*zlib_top*--report_level*estimate*B-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/*Z/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_lz77_compress_mm.cpp*X/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_huffman_enc_mm.cpp*T/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_treegen_mm.cpp*\/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_s2_pingpong_buffer.cpp*R/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src//zlib_top_loop.cpp2ï
\/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/advanced.ini5[advanced]
param=compiler.enableAutoPipelining=false
"Thu Jun  4 05:13:46 2020(¸µÓÙß.r(
$ae9c64b3-b2e0-4bbd-9fd5-9606235aab46"Thu Jun  4 05:13:58 2020(„íÔÙß.Zπ
xilinx_u250_xdma_201830_2.xpfmxilinx_u250_xdma_201830_2.dsaE/curr/software/Vitis/Vitis/2019.2/platforms/xilinx_u250_xdma_201830_2"OpenCL*Linux08Jù
bzlib_topT/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/a.xoY/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/zlib_lz77_compress_mm.cppW/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/zlib_huffman_enc_mm.cppS/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/zlib_treegen_mm.cpp[/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/zlib_s2_pingpong_buffer.cppQ/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/src/zlib_top_loop.cpp"Thu Jun  4 05:13:58 2020(ÎíÔÙß.b—
$c6670e50-ad40-42cd-acc4-bda082a0cd91
vivado_hlsn/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4/a/zlib_top/vivado_hls.log"ìvivado_hls -f /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4/a/zlib_top/zlib_top.tcl -messageDb vivado_hls.pb*
vivado_hls*-f*l/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4/a/zlib_top/zlib_top.tcl*
-messageDb*vivado_hls.pb"Thu Jun  4 05:13:58 2020(ÓíÔÙß.r(
$c6670e50-ad40-42cd-acc4-bda082a0cd91"Thu Jun  4 05:33:49 2020(”Ó∑ıß.r(
$c6670e50-ad40-42cd-acc4-bda082a0cd91"Thu Jun  4 05:33:50 2020(¥∑ıß.jz
t/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4_report/a/system_estimate_a.xtxt "Thu Jun  4 05:33:50 2020(æÙ∑ıß.j
y/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4_report/a/v++_compile_a_guidance.html "Thu Jun  4 05:33:50 2020(æÙ∑ıß.jt
n/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx/L2/tests/zlib_compress/hls4/v++_compile_a_guidance.pb "Thu Jun  4 05:33:50 2020(øÙ∑ıß.r(
$ae9c64b3-b2e0-4bbd-9fd5-9606235aab46