
Í
v++_compile_a$430e5c32-08e1-4998-86c5-a7c5af8e383e2|t/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4/.tlog/v++_compile_a.xtl 2..compile_summary 2..compile_summary.pb l/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/..compile_summary.pb"Fri Jul 24 03:44:41 2020(√Ü†˛∑.b≥
$ce8f955d-5014-4acb-92be-7ce73184ae00v++j/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4/a/a.steps.log"‡
/curr/software/Vitis/Vitis/2019.2/bin/unwrapped/lnx64.o/v++  --xp "vivado_prop:run.__KERNEL__.{STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS}={-directive sdx_optimization_effort_high}" --xp param:compiler.forceHlsDesignXmlGeneration=1 -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L1/include/hw -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/ -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/include/ -g -t sw_emu --platform /curr/software/Vitis/Vitis/2019.2/platforms/xilinx_u250_xdma_201830_2/xilinx_u250_xdma_201830_2.xpfm --save-temps --config /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/advanced.ini -DPARALLEL_BLOCK=8 --temp_dir hls4 --report_dir hls4_report -c -k zlib_top --report_level estimate -I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/ /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_lz77_compress_mm_new.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_huffman_enc_mm_new.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_treegen_mm_new.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_s2_pingpong_buffer.cpp /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_top_loop.cpp *P-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L1/include/hw*J-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/*N-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/include/*-g*-t*sw_emu*
--platform*d/curr/software/Vitis/Vitis/2019.2/platforms/xilinx_u250_xdma_201830_2/xilinx_u250_xdma_201830_2.xpfm*--save-temps*--config*d/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/advanced.ini*-DPARALLEL_BLOCK=8*
--temp_dir*hls4*--report_dir*hls4_report*-c*-k*zlib_top*--report_level*estimate*J-I/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/*f/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_lz77_compress_mm_new.cpp*d/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_huffman_enc_mm_new.cpp*`/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_treegen_mm_new.cpp*d/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_s2_pingpong_buffer.cpp*Z/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src//zlib_top_loop.cpp2ù
d/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/advanced.ini5[advanced]
param=compiler.enableAutoPipelining=false
"Fri Jul 24 03:44:41 2020(ƒÜ†˛∑.r(
$ce8f955d-5014-4acb-92be-7ce73184ae00"Fri Jul 24 03:44:52 2020(›·†˛∑.Zı
xilinx_u250_xdma_201830_2.xpfmxilinx_u250_xdma_201830_2.dsaE/curr/software/Vitis/Vitis/2019.2/platforms/xilinx_u250_xdma_201830_2"OpenCL*Linux08JŸ
jzlib_top\/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/a.xoe/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/zlib_lz77_compress_mm_new.cppc/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/zlib_huffman_enc_mm_new.cpp_/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/zlib_treegen_mm_new.cppc/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/zlib_s2_pingpong_buffer.cppY/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/src/zlib_top_loop.cpp"Fri Jul 24 03:44:52 2020(··†˛∑.bÈ
$5fc42cc7-b540-428c-8a5f-5898dd4709ca
vivado_hlsv/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4/a/zlib_top/vivado_hls.log"õvivado_hls -f /home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4/a/zlib_top/zlib_top.tcl -messageDb vivado_hls.pb*
vivado_hls*-f*t/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4/a/zlib_top/zlib_top.tcl*
-messageDb*vivado_hls.pb"Fri Jul 24 03:44:52 2020(‚·†˛∑.r(
$5fc42cc7-b540-428c-8a5f-5898dd4709ca"Fri Jul 24 03:55:26 2020(∫∑«˛∑.r(
$5fc42cc7-b540-428c-8a5f-5898dd4709ca"Fri Jul 24 03:55:26 2020(Ùπ«˛∑.jÇ
|/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4_report/a/system_estimate_a.xtxt "Fri Jul 24 03:55:27 2020(£æ«˛∑.jà
Å/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4_report/a/v++_compile_a_guidance.html "Fri Jul 24 03:55:27 2020(§æ«˛∑.j|
v/home/yuhang/test_acc_lib_nPe/acc_lib/compression_xilinx_new_ddr/L2/tests/zlib_compress/hls4/v++_compile_a_guidance.pb "Fri Jul 24 03:55:27 2020(•æ«˛∑.r(
$ce8f955d-5014-4acb-92be-7ce73184ae00