# 
# Hls run script generated by SDAccel
# 

open_project vgg16
set_top vgg16
add_files vgg16.cpp
open_solution solution_OCL_REGION_0
set_part xcku060-ffva1156-2-e
create_clock -period 240MHz -name default
config_rtl -register_reset
csynth_design
#export_design -format ipxact
close_project
puts "Vivado HLS completed successfully"
exit
