
#ifndef _CONV_3D_H
#define _CONV_3D_H

#define IMAGE_SIZE 1000
#define FILTER_SIZE 24
#define OUT_IMAGE_SIZE (IMAGE_SIZE - FILTER_SIZE + 1)

#define DATA_IN_LENGTH   (IMAGE_SIZE * IMAGE_SIZE * IMAGE_SIZE)
#define FILTER_IN_LENGTH (FILTER_SIZE * FILTER_SIZE * FILTER_SIZE)
#define DATA_OUT_LENGTH  (OUT_IMAGE_SIZE * OUT_IMAGE_SIZE * OUT_IMAGE_SIZE)

#define LENGTH_IN_TILE  (FILTER_SIZE * IMAGE_SIZE * IMAGE_SIZE)
#define LENGTH_OUT_TILE (OUT_IMAGE_SIZE * OUT_IMAGE_SIZE)

#define OVERLAP 2
#define PE 4

#define STEP ((IMAGE_SIZE - FILTER_SIZE) / PE + 1)
#define IN_DEPTH ((FILTER_SIZE - 1) + STEP)
#define IN_SIZE_TILE (IN_DEPTH * IMAGE_SIZE * IMAGE_SIZE)
#define IN_SIZE_ONE_CALL (IN_DEPTH * FILTER_SIZE * IMAGE_SIZE)
#define OUT_DEPTH STEP
#define OUT_SIZE_TILE (OUT_DEPTH * OUT_IMAGE_SIZE * OUT_IMAGE_SIZE)
#define OUT_SIZE_ONE_CALL (OUT_DEPTH * OUT_IMAGE_SIZE)
#define LAST_OUT_DEPTH (STEP-(STEP*PE-OUT_IMAGE_SIZE))
#define LAST_OUT_SIZE_ONE_CALL (LAST_OUT_DEPTH * OUT_IMAGE_SIZE)

#define CPU
#endif
