# 
# Hls run script generated by SDAccel
# 

open_project vgg16
set_top vgg16
add_files vgg16.cpp
add_files -tb main.cpp
add_files -tb vgg16_sw2.cpp
open_solution solution_0
set_part xcku060-ffva1156-2-e
create_clock -period 240MHz -name default
config_rtl -register_reset
config_compile -unsafe_math_optimizations
#csim_design
csynth_design
#cosim_design
export_design -format ipxact
close_project
puts "Vivado HLS completed successfully"
exit
