

if [ "$1" = "fpga" ]; then
/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc examples/cpp_classification/classification_fpga.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification/classification_fpga.o 2> .build_release/examples/cpp_classification/classification_fpga.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification/classification_fpga.o.warnings.txt; exit 1)

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc .build_release/examples/cpp_classification/classification_fpga.o -o .build_release/examples/cpp_classification/classification_fpga.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib

elif [ "$1" = "cpu" ]; then
gcc examples/cpp_classification/classification.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification/classification.o 2> .build_release/examples/cpp_classification/classification.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification/classification.o.warnings.txt; exit 1)

gcc .build_release/examples/cpp_classification/classification.o -o .build_release/examples/cpp_classification/classification.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib


elif [ "$1" = "cpu_batch" ]; then
gcc examples/cpp_classification/classification_batch.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY  -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification/classification_batch.o 2> .build_release/examples/cpp_classification/classification_batch.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification/classification_batch.o.warnings.txt; exit 1)

gcc .build_release/examples/cpp_classification/classification_batch.o -o .build_release/examples/cpp_classification/classification_batch.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib

elif [ "$1" = "fpga_batch" ]; then

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc examples/cpp_classification/classification_fpga_batch.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification/classification_fpga_batch.o 2> .build_release/examples/cpp_classification/classification_fpga_batch.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification/classification_fpga_batch.o.warnings.txt; exit 1)

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc .build_release/examples/cpp_classification/classification_fpga_batch.o -o .build_release/examples/cpp_classification/classification_fpga_batch.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib

elif [ "$1" = "fpga_batch_sda" ]; then

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc examples/cpp_classification/classification_fpga_batch_sda.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification/classification_fpga_batch_sda.o 2> .build_release/examples/cpp_classification/classification_fpga_batch_sda.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification/classification_fpga_batch_sda.o.warnings.txt; exit 1)

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc .build_release/examples/cpp_classification/classification_fpga_batch_sda.o -o .build_release/examples/cpp_classification/classification_fpga_batch_sda.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib

elif [ "$1" = "fpga_batch_sda_half" ]; then

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc examples/cpp_classification_fpga_half/classification_fpga_half.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -DHLS_NO_XIL_FPO_LIB -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification_fpga_half/classification_fpga_half.o 2> .build_release/examples/cpp_classification_fpga_half/classification_fpga_half.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification_fpga_half/classification_fpga_half.o.warnings.txt; exit 1)

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc .build_release/examples/cpp_classification_fpga_half/classification_fpga_half.o -o .build_release/examples/cpp_classification_fpga_half/classification_fpga_half.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -DHLS_NO_XIL_FPO_LIB -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib

elif [ "$1" = "fpga_batch_sda_fx" ]; then

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc examples/cpp_classification_fpga_fx/classification_fpga.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -DHLS_NO_XIL_FPO_LIB -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification_fpga_fx/classification_fpga.o 2> .build_release/examples/cpp_classification_fpga_fx/classification_fpga.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification_fpga_fx/classification_fpga.o.warnings.txt; exit 1)

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc .build_release/examples/cpp_classification_fpga_fx/classification_fpga.o -o .build_release/examples/cpp_classification_fpga_fx/classification_fpga.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -DHLS_NO_XIL_FPO_LIB -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib

elif [ "$1" = "fpga_batch_sda_fxdyn" ]; then

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc examples/cpp_classification_fpga_fxdyn/classification_fpga.cpp -g -Wall -D FPGA_DEVICE -D C_KERNEL -MMD -MP -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -DHLS_NO_XIL_FPO_LIB -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -c -o .build_release/examples/cpp_classification_fpga_fxdyn/classification_fpga.o 2> .build_release/examples/cpp_classification_fpga_fxdyn/classification_fpga.o.warnings.txt \
		|| (cat .build_release/examples/cpp_classification_fpga_fxdyn/classification_fpga.o.warnings.txt; exit 1)

/curr/software/Xilinx/SDAccel/2015.3/lnx64/tools/gcc/bin/gcc .build_release/examples/cpp_classification_fpga_fxdyn/classification_fpga.o -o .build_release/examples/cpp_classification_fpga_fxdyn/classification_fpga.bin -g -Wall -D FPGA_DEVICE -D C_KERNEL -pthread -fPIC -DNDEBUG -O2 -DUSE_OPENCV -DCPU_ONLY -DHLS_NO_XIL_FPO_LIB -I/curr/software/Xilinx/SDAccel/2015.3/Vivado_HLS/include -L/curr/hanhu/sdaccel_library/pkg_ku3/pcie -L/curr/software/Xilinx/SDAccel/2015.3/runtime/lib/x86_64 -lxilinxopencl -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/curr/chenzhang/tool/boost_1_55_0/install/include -I/curr/chenzhang/tool/opencv/opencv_install/include -I/curr/chenzhang/tool/glog-0.3.3/build/install/include -I/curr/chenzhang/tool/gflags-master/build/include -I/curr/chenzhang/tool/mdb/libraries/liblmdb -I/curr/diwu/tools/protobuf-2.5.0/build/install/include -I/curr/chenzhang/tool/hdf5_install/include -I/curr/chenzhang/tool/cuda-6.5/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/curr/chenzhang/tool/ATLAS/build/install/include -Wall -Wno-sign-compare -lcaffe -L/usr/local/lib/python2.7 -L/curr/chenzhang/tool/boost_1_55_0/install/lib -L/curr/chenzhang/tool/opencv/opencv_install/lib -L/curr/chenzhang/tool/glog-0.3.3/build/install/lib -L/curr/chenzhang/tool/gflags-master/build/lib -L/curr/chenzhang/tool/mdb/libraries/liblmdb -L/curr/diwu/tools/protobuf-2.5.0/build/install/lib -L/curr/chenzhang/tool/hdf5_install/lib -L/curr/chenzhang/tool/cuda-6.5/bin -L/usr/local/lib -L/usr/lib -L/curr/chenzhang/tool/ATLAS/build/install/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lm -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas \
		-Wl,-rpath,\$ORIGIN/../../lib

else 
   echo "Commandline: sh compile.sh [device](cpu/fpga/cpu_batch/fpga_batch) " 
fi

